Create vhazlewo.md
fdac22/students pull request #70
Opened 2022-08-28 21:09 UTC by uxvictor

Victor's paragraph

2022-08-28 21:35 UTC, robobenklein requested changes
Can you add 'I am' or 'My name is' on the first line so the regex will p pick up your name?

2022-08-29 11:56 UTC, uxvictor commented
Done

From: Ben Klein ***@***.***>
Sent: Sunday, August 28, 2022 5:36 PM
To: fdac22/students ***@***.***>
Cc: Hazlewood, Victor ***@***.***>; Author ***@***.***>
Subject: Re: [fdac22/students] Create vhazlewo.md (PR #70)

You don't often get email from ***@***.******@***.***>. Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

@robobenklein requested changes on this pull request.

Can you add 'I am' or 'My name is' on the first line so the regex will p pick up your name?

-
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ffdac22%2Fstudents%2Fpull%2F70%23pullrequestreview-1087915974&data=05%7C01%7Cvhazlewo%40utk.edu%7C1792a66f95f94029968908da893d5180%7C515813d9717d45dd9eca9aa19c09d6f9%7C0%7C0%7C637973193709054258%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=SBeWO%2BktKyfdKG3QHmAhALd6JJAFNlqHJVwGqDVU%2BNM%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FA2ZFBT2LQRGEDLEM6RW4DA3V3PLUPANCNFSM573WF6HQ&data=05%7C01%7Cvhazlewo%40utk.edu%7C1792a66f95f94029968908da893d5180%7C515813d9717d45dd9eca9aa19c09d6f9%7C0%7C0%7C637973193709210483%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=DaZ4u6vgYAqhdyebg%2FOvuBAw6CmAu7NVQv1%2B3Q%2Fe86U%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>

2022-08-29 21:37 UTC, uxvictor commented
I added "I am".  Hopefully, that did the trick.

-Victor

From: Ben Klein ***@***.***>
Sent: Sunday, August 28, 2022 5:36 PM
To: fdac22/students ***@***.***>
Cc: Hazlewood, Victor ***@***.***>; Author ***@***.***>
Subject: Re: [fdac22/students] Create vhazlewo.md (PR #70)

You don't often get email from ***@***.******@***.***>. Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

@robobenklein requested changes on this pull request.

Can you add 'I am' or 'My name is' on the first line so the regex will p pick up your name?

-
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ffdac22%2Fstudents%2Fpull%2F70%23pullrequestreview-1087915974&data=05%7C01%7Cvhazlewo%40utk.edu%7C1792a66f95f94029968908da893d5180%7C515813d9717d45dd9eca9aa19c09d6f9%7C0%7C0%7C637973193709054258%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=SBeWO%2BktKyfdKG3QHmAhALd6JJAFNlqHJVwGqDVU%2BNM%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FA2ZFBT2LQRGEDLEM6RW4DA3V3PLUPANCNFSM573WF6HQ&data=05%7C01%7Cvhazlewo%40utk.edu%7C1792a66f95f94029968908da893d5180%7C515813d9717d45dd9eca9aa19c09d6f9%7C0%7C0%7C637973193709210483%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=DaZ4u6vgYAqhdyebg%2FOvuBAw6CmAu7NVQv1%2B3Q%2Fe86U%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>

2022-08-29 22:05 UTC, robobenklein approved these changes

2022-08-29 22:05 UTC, merged